### ISSUE TITLE
Simplifying bootstrapping with clean data representation

### ISSUE THREAD

**Issue by triska** [datavetaren/prologcoin#1]
I would like to make a small suggestion that may help to simplify `lr_gen.pl`.

The idea is to reconsider how the rules in `prolog_grammar.pl` are represented.

Currently, you are using Prolog *clauses* to state the rules. This certainly seems straight-forward, but has a major disadvantage: The Prolog representation of clauses is called *defaulty*, as opposed to [*clean*](https://www.metalevel.at/prolog/data#clean). This is the reason why you need so many `!/0` to reason about these clauses.

The key insight to achieving a clean representation is to be aware that we have a lot of freedom in how we *could* represent the exact same rules instead.

For example, consider the following fragment of the rules:

<pre>
term(N) :- subterm('<'(N)), op(N, xf), subterm('<'(N)).
term(N) :- subterm(N), op(N, yf).
</pre>

We could also represent this as:

<pre>
term(N) :- [subterm('<'(N)), op(N, xf), subterm('<'(N))].
term(N) :- [subterm(N), op(N, yf)].
</pre>

In the above, I have used **lists** to get rid of the defaultiness at the outermost layer. Now, these rules are of the form:

<pre>
Head :- List.
</pre>

and we can easily process the body with `maplist/3` and related predicates. Importantly, we can now *symbolically* distinguish the empty list `[]` from a list with at least one element&nbsp;`[E|_]`.

Second, we can apply the same idea to get rid of the defaultiness at the inner layer, using for example:

  - `meta(R)` for a rule `R` that is to be interpreted at the meta-level
  - `nt(R)` for a rule `R` that is a nonterminal of the actual grammar.

For example, it *could* look like this:

<pre>
term(N) :- [nt(subterm('<'(N))), meta(op(N, xf)), nt(subterm('<'(N)))].
term(N) :- [nt(subterm(N)), meta(op(N, yf))].
</pre>

I am not saying that this is correct for this particular example, but I am giving this as one case where it *could* make sense to symbolically distinguish between two different *kinds* of rules by supplying suitable wrappers.

This will allow you to process the whole grammar more easily, relying on *pattern&nbsp;matching* to distinguish the different cases. You can use any number of additional wrappers at your discretion to introduce additional categories of elements.

Of course, the result will no longer be directly executable in Prolog, **but** you can easily run it with a [**meta-interpreter**](https://www.metalevel.at/acomip/).

**Comment by datavetaren** [comment]
Hi Markus,

Thanks for your suggestions but I'm rewriting the grammar. It's impossible to get a clean LALR(1) parser from the published grammar.  And don't focus too much on lr_gen. It's purpose is to produce C++ code that will be plugged into the parser.

You'll see more of it in my next commit. Interesting that you're following my repo.

Thanks,
Datavetaren
