### ISSUE TITLE
Small point about <- syntax

### ISSUE THREAD

**Issue by triska** [datavetaren/prologcoin#2]
Regarding the question in the project description:

>  ":-" looks ugly and why not "<-" ?

The reason for such issues is that Prolog is frequently used for theorem provers, and therefore the native Prolog syntax is chosen in such a way that it stays out of the way of patterns that may be useful to represent data in *user&nbsp;code*.

This is the reason why we write for example `=<` instead of `<=` (as in most other languages) to denote "less than or equal to": `<=` looks like an *arrow*, and that is kept usable for applications.

If you want, you can always define your custom infix operators and use them instead!

**Comment by datavetaren** [comment]
I know all that but :- is still questionable. It feels that it is using the same heritage as Pascal which used := for assignment, when <- would look much better. But then you'll get the tokenization problem with x<-2 (x less than -2).

**Comment by triska** [comment]
OK! Only a bit of trivia, so I am closing this issue.
